language: node_js 
node_js:
  - 12 
services:
  - docker 


#Pre-testing install 
install: 
  - echo "nothing needs to be installed"


#Scripts to be run such as tests 
before_script:
  - echo "no tests"


script:
  - docker --version  # prints theversion for loggin 
  - docker build -t weatherlens-fe . 
  - docker tag weatherlens-fe fansua/weatherlens-fe:latest

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push fansua/weatherlens-fe